name: Run Hello Script

# Trigger this action on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run hello.sh script
      run: |
        chmod +x hello.sh
        ./hello.sh
